#!/bin/bash

axel https://ftp.gnu.org/gnu/ncurses/ncurses-6.3.tar.gz
tar -xzf ncurses-6.3.tar.gz
cd ncurses-6.3

CC=clang CXX=clang++ CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native" LDFLAGS="-O3 -march=native -flto" ./configure --prefix=/usr/local --enable-widec --enable-static --disable-shared


make
sudo make install
